version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports:
      - "5432:5432"
    networks: 
      - app_net

  app:
    build: .
    depends_on: 
      - db
    ports:
      - "3333:3333"
    networks: 
      - app_net
    command: yarn dev
    

networks: 
  app_net: